### ISSUE TITLE
Papers that might be interesting

### ISSUE THREAD

**Issue by agosiewska** [MI2DataLab/survxai#11]
- [On Ranking in Survival Analysis: Bounds on the Concordance Index ](https://papers.nips.cc/paper/3375-on-ranking-in-survival-analysis-bounds-on-the-concordance-index.pdf)
- [iSurvive: An Interpretable, Event-time Prediction Model for mHealth](http://proceedings.mlr.press/v70/dempsey17a/dempsey17a.pdf)

**Comment by agosiewska** [comment]
[Survival Model Predictive Accuracy and ROC Curves](https://biostats.bepress.com/cgi/viewcontent.cgi?article=1051&context=uwbiostat)

**Comment by pbiecek** [comment]
@agosiewska shall we close this issue?

**Comment by agosiewska** [comment]
Yes, I'll close it
