### ISSUE TITLE
Corrections to JOSS manuscript

### ISSUE THREAD

**Issue by hiendn** [MI2DataLab/survxai#18]
Please make the corrections from the marked up file that has been attached. Please also conduct a thorough proof reading once you have made the corrections, since I may have missed some things.

[10.21105.joss.00961.pdf](https://github.com/MI2DataLab/survxai/files/2401202/10.21105.joss.00961.pdf)

**Comment by dirmeier** [comment]
In addition to the corrections mentioned by @hiendn, please find a list of minor revisions and comments below:
- There are many typos and grammatical errors. Please make sure to remove them.
- Even though I understand your point, from the intro it does not get clear to someone not working in the field how survival analysis models and your tool are related to NNs or RFs, or rather it does not get enough emphasis. You motivate your problem with the interpretability of models that are "complex in structure", yet only show *local method* plots for a simple Cox proportional hazard model where intepretation of the coefficients is relatively simple, right? I understand that this is only a simple use case that could be generalized to more complex problems, but I believe you could maybe better motivate this, e.g. by showing a more elaborate use case, for instance when the Cox model is parametrized by an NN.  This is however only a comment and I might be wrong.
- Figure 1: why do you only describe the middle panel and not the others? E.g. what are the colors for `bili`?
- Hyperlink of Eleuteri paper does not work. Also check other hyperlinks please.

**Comment by agosiewska** [comment]
Thank you for your comments.
We've made the corrections and @AleksandraDabrowska rebuilded the pdf.
https://github.com/openjournals/joss-reviews/issues/961
