### ISSUE TITLE
Default methods

### ISSUE THREAD

**Issue by dirmeier** [MI2DataLab/survxai#20]
If implementing a `default` method for an S3 function, I believe you should use
```{r}
explain  <- function() UseMethod("explain")
```
instead of
```{r}
explain  <- explain.default
```
This would remove the second entry in the function's docu.

**Comment by agosiewska** [comment]
@dirmeier Thanks, I changed it according to your suggestion.

**Comment by dirmeier** [comment]
Cool, thank you.
