### ISSUE TITLE
Values for variables in the plot strip

### ISSUE THREAD

**Issue by pbiecek** [MI2DataLab/survxai#9]
right now there is a variable name 'age'
it should be connected with value for a selected point 'age = 25'

**Comment by pbiecek** [comment]
@AleksandraDabrowska I do not see any change in https://mi2datalab.github.io/survxai/articles/Local_explanations.html

**Comment by AleksandraDabrowska** [comment]
@pbiecek I have just updated the pkg down (commit 0cb6aa63540a3e87073fa6411284b39241db245b). You can find changed plots for breakdown and ceteris paribus in vignette for local explanations and vignette with three models.

**Comment by pbiecek** [comment]
thanks
